import * as v from 'valibot';

const REVERSE_DOMAIN = /^[a-z0-9]+(\.[\w-]+)+$/i;
const DEVICE_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// Verbatim copy of capgo-backend/.../plugins/stats_actions.ts:4-65. Must stay
// in lock-step with upstream or we'll reject events the plugin emits.
export const ALLOWED_STATS_ACTIONS = [
	'ping',
	'delete',
	'reset',
	'set',
	'get',
	'set_fail',
	'update_fail',
	'download_fail',
	'windows_path_fail',
	'canonical_path_fail',
	'directory_path_fail',
	'unzip_fail',
	'low_mem_fail',
	'download_0',
	'download_10',
	'download_20',
	'download_30',
	'download_40',
	'download_50',
	'download_60',
	'download_70',
	'download_80',
	'download_90',
	'download_complete',
	'download_manifest_start',
	'download_manifest_complete',
	'download_zip_start',
	'download_zip_complete',
	'download_manifest_file_fail',
	'download_manifest_checksum_fail',
	'download_manifest_brotli_fail',
	'decrypt_fail',
	'app_moved_to_foreground',
	'app_moved_to_background',
	'uninstall',
	'needPlanUpgrade',
	'missingBundle',
	'noNew',
	'disablePlatformIos',
	'disablePlatformAndroid',
	'disableAutoUpdateToMajor',
	'cannotUpdateViaPrivateChannel',
	'disableAutoUpdateToMinor',
	'disableAutoUpdateToPatch',
	'channelMisconfigured',
	'disableAutoUpdateMetadata',
	'disableAutoUpdateUnderNative',
	'disableDevBuild',
	'disableProdBuild',
	'disableEmulator',
	'disableDevice',
	'cannotGetBundle',
	'checksum_fail',
	'NoChannelOrOverride',
	'setChannel',
	'getChannel',
	'rateLimited',
	'disableAutoUpdate',
	'InvalidIp',
	'blocked_by_server_url'
] as const;

export const StatsEventSchema = v.object({
	app_id: v.pipe(v.string(), v.regex(REVERSE_DOMAIN), v.maxLength(128)),
	device_id: v.pipe(v.string(), v.minLength(1), v.maxLength(36), v.regex(DEVICE_ID)),
	platform: v.pipe(v.string(), v.minLength(1), v.maxLength(32)),
	version_name: v.pipe(v.string(), v.minLength(1), v.maxLength(128)),
	old_version_name: v.optional(v.pipe(v.string(), v.maxLength(128))),
	version_os: v.pipe(v.string(), v.maxLength(64)),
	version_code: v.optional(v.pipe(v.string(), v.maxLength(64))),
	version_build: v.optional(v.pipe(v.string(), v.maxLength(64))),
	action: v.optional(v.picklist(ALLOWED_STATS_ACTIONS)),
	custom_id: v.optional(v.pipe(v.string(), v.maxLength(36))),
	channel: v.optional(v.pipe(v.string(), v.maxLength(64))),
	defaultChannel: v.optional(v.pipe(v.string(), v.maxLength(64))),
	plugin_version: v.optional(v.pipe(v.string(), v.maxLength(32))),
	is_emulator: v.boolean(),
	is_prod: v.boolean(),
	key_id: v.optional(v.pipe(v.string(), v.maxLength(20)))
});

export type StatsEventInput = v.InferOutput<typeof StatsEventSchema>;
